disabled = false
languageCode = "zh-cn"
languageName = "简体中文"
weight = 2
title = "ルース毛"

[params]
  displayName = "简体中文"
  isoCode = "zh"
  rtl = false
  dateFormat = "2006 January 2"
#   logo = "img/icon.png"
#   secondaryLogo = "img/secondary-logo.png"
  description = "你好"
  copyright = "© 2026- ルース毛"

[params.author]
  name = "ルース毛"
  email = "justlouis0213@gmail.com"
  image = "img/logo.png"
  imageQuality = 96
  headline = "ˋ( ° ▽、° ) "
  bio = "中国人并且是全所为模仿者并且是霜奶仙"
  links = [
#     { email = "mailto:hello@your_domain.com" },
#     { link = "https://link-to-some-website.com/" },
#     { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
#     { apple = "https://www.apple.com" },
    { bilibili = "https://space.bilibili.com/3493264049047661" },
#     { blogger = "https://username.blogspot.com/" },
#     { bluesky = "https://bsky.app/profile/username" },
#     { codepen = "https://codepen.io/username" },
#     { dev = "https://dev.to/username" },
    { discord = "https://discordapp.com/users/936907235207032872" },
#     { dribbble = "https://dribbble.com/username" },
#     { facebook = "https://facebook.com/username" },
#     { flickr = "https://www.flickr.com/photos/username/" },
#     { foursquare = "https://foursquare.com/username" },
    { github = "https://github.com/ruusuge" },
#     { gitlab = "https://gitlab.com/username" },
#     { google = "https://www.google.com/" },
#     { hashnode = "https://username.hashnode.dev" },
#     { instagram = "https://instagram.com/username" },
#     { itch-io = "https://username.itch.io" },
#     { keybase = "https://keybase.io/username" },
#     { keyoxide = "https://keyoxide.org/URI" },
#     { kickstarter = "https://www.kickstarter.com/profile/username" },
#     { lastfm = "https://lastfm.com/user/username" },
#     { linkedin = "https://linkedin.com/in/username" },
#     { mastodon = "https://mastodon.instance/@username" },
#     { matrix = "https://matrix.to/#/URI" },
#     { medium = "https://medium.com/username" },
#     { microsoft = "https://www.microsoft.com/" },
    { misskey = "https://misskey.io/@ruusuge" },
#     { orcid = "https://orcid.org/userid" },
    { otomadsite = "https://otomad.site/@ruusuge" },
#     { patreon = "https://www.patreon.com/username" },
#     { pinterest = "https://pinterest.com/username" },
    { qq = "https://qm.qq.com/q/db4FlC2wEw" },
#     { reddit = "https://reddit.com/user/username" },
#     { researchgate = "https://www.researchgate.net/profile/username" },
#     { signal = "https://signal.me/#eu/userid" },
#     { slack = "https://workspace.url/team/userid" },
#     { snapchat = "https://snapchat.com/add/username" },
#     { soundcloud = "https://soundcloud.com/username" },
#     { spotify = "https://open.spotify.com/user/userid" },
#     { stack-overflow = "https://stackoverflow.com/users/userid/username" },
#     { steam = "https://steamcommunity.com/profiles/userid" },
#     { telegram = "https://t.me/username" },
#     { threads = "https://www.threads.net/@username" },
#     { tiktok = "https://tiktok.com/@username" },
#     { tumblr = "https://username.tumblr.com" },
#     { twitch = "https://twitch.tv/username" },
    { twitter = "https://twitter.com/ruusuge_" },
#     { x-twitter = "https://twitter.com/username" },
#     { whatsapp = "https://wa.me/phone-number" },
    { youtube = "https://www.youtube.com/@%E3%83%AB%E3%83%BC%E3%82%B9%E6%AF%9B" },
#     { ko-fi = "https://ko-fi.com/username" },
#     { codeberg = "https://codeberg.org/username"},
#     { printables = "https://www.printables.com/@username"}
  ]
